### PR TITLE
Add admin photos index table

### LINKED ISSUE #159: Admin studio dash shows studio photos table
Table with photo id, name, status, activate/deactivate buttons, anything else??

### PR DESCRIPTION
**Pull request by scottfirestone**
Add button on admim studio dashboard for manage photos points to admin photos index view
Add admin photos index with table showing all photos with links, edit, status, and status change
Add route for admin photos index

closes #159

### CODE REVIEW

**Comment by scottfirestone** [comment]
I decided to have a separate link to another view rather than put the photos table on the dashboard. Let me know if you have strong feelings about this @adriennedomingus @brianrip

**Comment by brianrip** [comment]
I am good with it.

**Comment by scottfirestone** [comment]
Just fixed a merge conflict. Ready to be reviewed.

**Comment by adriennedomingus** [comment]
I'm good with it too. Merging

**Pull request merged**
